#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Publication
GROUP=com.verimsolution
VERSION_NAME=1.0.0
POM_ARTIFACT_ID=hugeiconskmp
POM_NAME=HugeiconsKMP
POM_DESCRIPTION=Kotlin Multiplatform Compose icon library for Hugeicons assets.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/plelouch7/KMP-Hugeicons-
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/plelouch7/KMP-Hugeicons-
POM_SCM_CONNECTION=scm:git:https://github.com/plelouch7/KMP-Hugeicons-.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/plelouch7/KMP-Hugeicons-.git
POM_DEVELOPER_ID=plelouch7
POM_DEVELOPER_NAME=plelouch7
POM_DEVELOPER_URL=https://github.com/plelouch7

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.builtInKotlin=false
android.newDsl=false
